package me.rerere.workspace
import java.io.File
import java.nio.file.Files

class RootfsPatcher {
    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        val etcDir = File(linuxDir, "etc")
        if (!etcDir.isDirectory) return

        // Termux 模式：保留 Termux 自带的 resolv.conf，不覆盖
        if (options.termuxMode) {
            ensureTermuxResolvConf(etcDir, options.nameservers)
        } else {
            ensureRootfsDns(etcDir, options.nameservers)
        }

        ensureHosts(etcDir, options.hostname)
        ensureHostname(etcDir, options.hostname)
        ensureLocale(etcDir, options.locale)
        ensureGroupNames(etcDir, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
        ensureTempDirs(linuxDir)

        // Termux 模式：额外配置 apt 源和必要目录
        if (options.termuxMode) {
            ensureTermuxAptSources(etcDir)
            ensureTermuxDirs(linuxDir)
        }
    }

    private fun ensureTermuxResolvConf(
        etcDir: File,
        nameservers: List<String>,
    ) {
        val resolvConf = File(etcDir, "resolv.conf")
        // 如果 resolv.conf 已存在且非空，保留不动（Termux 有自己的 DNS 管理）
        if (resolvConf.exists() && resolvConf.length() > 0) {
            return
        }
        // 否则写入默认 DNS
        val servers = nameservers.filter { it.isNotBlank() }.distinct().take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }
        resolvConf.writeText(
            buildString {
                appendLine("# Generated by RikkaHub workspace (Termux mode)")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            }
        )
    }

    private fun ensureTermuxAptSources(etcDir: File) {
        val sourcesDir = File(etcDir, "apt/sources.list.d")
        sourcesDir.mkdirs()

        // Termux 官方 apt 源
        val termuxMain = File(sourcesDir, "termux-main.list")
        if (!termuxMain.exists()) {
            termuxMain.writeText(
                "deb https://packages.termux.dev/apt/termux-main/ stable main\n"
            )
        }

        // Termux root 包源（可选，用于 proot 环境安装需要 root 的工具）
        val termuxRoot = File(sourcesDir, "termux-root.list")
        if (!termuxRoot.exists()) {
            termuxRoot.writeText(
                "deb https://packages.termux.dev/apt/termux-root/ stable root\n"
            )
        }
    }

    private fun ensureTermuxDirs(linuxDir: File) {
        // Termux 需要的额外目录
        listOf(
            "usr/bin/applets",
            "usr/share/termux",
            "var/lib/apt/lists",
            "var/cache/apt/archives",
            "usr/etc/terminfo",
        ).forEach { path ->
            File(linuxDir, path).mkdirs()
        }

        // 确保 tmp 目录权限正确
        listOf(File(linuxDir, "tmp"), File(linuxDir, "var/tmp")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
    }

    private fun ensureRootfsDns(
        etcDir: File,
        nameservers: List<String>,
    ) {
        val resolvConf = File(etcDir, "resolv.conf")
        val shouldWrite = when {
            Files.isSymbolicLink(resolvConf.toPath()) -> true
            !resolvConf.exists() -> true
            !resolvConf.isFile -> true
            else -> resolvConf.readText()
                .lineSequence()
                .filter { it.trimStart().startsWith("nameserver ") }
                .none { line ->
                    val server = line.trim().removePrefix("nameserver").trim()
                    server.isNotBlank() && server !in LOCAL_RESOLVERS
                }
        }
        if (!shouldWrite) return

        if (resolvConf.exists() || Files.isSymbolicLink(resolvConf.toPath())) {
            resolvConf.delete()
        }

        val servers = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }
        resolvConf.writeText(
            buildString {
                appendLine("# Generated by RikkaHub workspace.")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            }
        )
    }

    private fun ensureHosts(etcDir: File, hostname: String) {
        val hosts = File(etcDir, "hosts")
        val lines = if (hosts.isFile) hosts.readLines() else emptyList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        hosts.parentFile?.mkdirs()
        hosts.appendText(
            buildString {
                if (hosts.exists() && hosts.length() > 0 && !hosts.readText().endsWith('\n')) {
                    appendLine()
                }
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            }
        )
    }

    private fun ensureHostname(etcDir: File, hostname: String) {
        val target = File(etcDir, "hostname")
        if (target.isFile && target.readText().trim().isNotBlank()) return
        target.writeText("${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(etcDir: File, locale: String) {
        val defaultDir = File(etcDir, "default").apply { mkdirs() }
        val target = File(defaultDir, "locale")
        val lines = if (target.isFile) target.readLines().toMutableList() else mutableListOf()
        if (lines.any { it.trim().startsWith("LANG=") }) return
        lines += "LANG=$locale"
        target.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }

    private fun ensureGroupNames(etcDir: File, groupIds: List<Long>) {
        val target = File(etcDir, "group")
        if (!target.exists()) {
            target.writeText("root:x:0:\n")
        }
        val lines = target.readLines().toMutableList()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty()) return
        target.appendText(
            buildString {
                if (target.length() > 0 && !target.readText().endsWith('\n')) {
                    appendLine()
                }
                additions.forEach { appendLine(it) }
            }
        )
    }

    private fun ensureTempDirs(linuxDir: File) {
        listOf("tmp", "var/tmp", "root").forEach { path ->
            File(linuxDir, path).mkdirs()
        }
        listOf(File(linuxDir, "tmp"), File(linuxDir, "var/tmp")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
        File(linuxDir, "root").apply {
            setReadable(true, true)
            setWritable(true, true)
            setExecutable(true, true)
        }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val MAX_DNS_SERVERS = 3
        private const val DEFAULT_HOSTNAME = "localhost"
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val LOCAL_RESOLVERS = setOf(
            "127.0.0.1",
            "127.0.0.53",
            "::1",
        )
        private val DEFAULT_DNS_SERVERS = listOf(
            "1.1.1.1",
            "8.8.8.8",
            "223.5.5.5",
        )
    }
}

data class RootfsPatchOptions(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
    val termuxMode: Boolean = false,
)
